/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicadeejercicios;

import java.awt.event.KeyEvent;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class Contador extends javax.swing.JPanel {

    /**
     * Creates new form Contador
     */
    private Interfaz inter;
    public Contador(Interfaz inter) {
        initComponents();
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo3 = new javax.swing.JLabel();
        TFEntrada = new javax.swing.JTextField();
        TFSalida = new javax.swing.JTextField();
        LblTitulo1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        LblTitulo4 = new javax.swing.JLabel();
        TFSalida1 = new javax.swing.JTextField();
        LblTitulo5 = new javax.swing.JLabel();
        TFSalida2 = new javax.swing.JTextField();
        LblTitulo6 = new javax.swing.JLabel();
        TFSalida3 = new javax.swing.JTextField();

        LblTitulo3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo3.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo3.setText("Positivos");
        LblTitulo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFEntrada.setBackground(new java.awt.Color(67, 153, 161));
        TFEntrada.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        TFEntrada.setForeground(new java.awt.Color(40, 51, 55));
        TFEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEntradaActionPerformed(evt);
            }
        });
        TFEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEntradaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFEntradaKeyTyped(evt);
            }
        });

        TFSalida.setBackground(new java.awt.Color(67, 153, 161));
        TFSalida.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        TFSalida.setForeground(new java.awt.Color(40, 51, 55));
        TFSalida.setEnabled(false);
        TFSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalidaActionPerformed(evt);
            }
        });

        LblTitulo1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo1.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo1.setText("Indique cuantos elementos introducirá");
        LblTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnVolver.setBackground(new java.awt.Color(40, 51, 55));
        BtnVolver.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(197, 226, 208));
        BtnVolver.setText("Volver");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnVolverMouseExited(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Consolas", 1, 32)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("CONTADOR");
        LblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LblTitulo4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo4.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo4.setText("Negativos");
        LblTitulo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFSalida1.setBackground(new java.awt.Color(67, 153, 161));
        TFSalida1.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        TFSalida1.setForeground(new java.awt.Color(40, 51, 55));
        TFSalida1.setEnabled(false);
        TFSalida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalida1ActionPerformed(evt);
            }
        });

        LblTitulo5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo5.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo5.setText("Pares");
        LblTitulo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFSalida2.setBackground(new java.awt.Color(67, 153, 161));
        TFSalida2.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        TFSalida2.setForeground(new java.awt.Color(40, 51, 55));
        TFSalida2.setEnabled(false);
        TFSalida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalida2ActionPerformed(evt);
            }
        });

        LblTitulo6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo6.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo6.setText("Impares");
        LblTitulo6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFSalida3.setBackground(new java.awt.Color(67, 153, 161));
        TFSalida3.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        TFSalida3.setForeground(new java.awt.Color(40, 51, 55));
        TFSalida3.setEnabled(false);
        TFSalida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalida3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(TFSalida3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(124, 124, 124)
                                    .addComponent(TFSalida2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(TFSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(LblTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(86, 86, 86)))))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblTitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(LblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(276, 276, 276)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LblTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(LblTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTitulo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTitulo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSalida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTitulo6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSalida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    //Ejercicio 10
    public void numerosMaker(int [] numeros, int n){
        if (n<numeros.length){
            
            numeros[n]=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número a agregar")); n++;
            numerosMaker(numeros, n);
        }
        else{
            contador(numeros, 0, 0, 0);
        }
    }
    public void contador(int [] numeros, int pa,int im, int i){
        int po=0; int ne=0;
        if (i<numeros.length){
            if (numeros[i]%2==0){
                pa++;i++;
                contador(numeros, pa, im, i);
            }
            else{
                im++;i++;
                contador(numeros, pa, im, i++);
            }
        }
        
        else{
            for (int n=0; n<numeros.length;n++){
                if (numeros[n]>0){
                    po+=numeros[n];
                }
                else{
                    ne+=numeros[n];
                }
            }
            TFSalida.setText(String.valueOf(po));
            TFSalida1.setText(String.valueOf(ne));
            TFSalida2.setText(String.valueOf(pa));
            TFSalida3.setText(String.valueOf(im));
        }
    }
    
    
    
    
    private void TFEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEntradaActionPerformed

    private void TFEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            int [] numeros = new int[Integer.parseInt(TFEntrada.getText())];
            numerosMaker(numeros, 0);
        }
    }//GEN-LAST:event_TFEntradaKeyPressed

    private void TFEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyTyped

    }//GEN-LAST:event_TFEntradaKeyTyped

    private void TFSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalidaActionPerformed

    private void BtnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseEntered
        inter.ColorSelected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseEntered

    private void BtnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseExited
        inter.ColorUnselected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseExited

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        inter.op();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void TFSalida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalida1ActionPerformed

    private void TFSalida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalida2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalida2ActionPerformed

    private void TFSalida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalida3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalida3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo3;
    private javax.swing.JLabel LblTitulo4;
    private javax.swing.JLabel LblTitulo5;
    private javax.swing.JLabel LblTitulo6;
    private javax.swing.JTextField TFEntrada;
    private javax.swing.JTextField TFSalida;
    private javax.swing.JTextField TFSalida1;
    private javax.swing.JTextField TFSalida2;
    private javax.swing.JTextField TFSalida3;
    // End of variables declaration//GEN-END:variables
}
