/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicadeejercicios;

import java.awt.event.KeyEvent;

/**
 *
 * @author Guillermo
 */
public class Fibonacci extends javax.swing.JPanel {

    /**
     * Creates new form Fibonacci
     */
    private Interfaz inter;
    public Fibonacci(Interfaz inter) {
        initComponents();
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFEntrada = new javax.swing.JTextField();
        LblTitulo1 = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAMovimientos = new javax.swing.JTextArea();
        BtnVolver = new javax.swing.JButton();

        TFEntrada.setBackground(new java.awt.Color(67, 153, 161));
        TFEntrada.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        TFEntrada.setForeground(new java.awt.Color(40, 51, 55));
        TFEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEntradaActionPerformed(evt);
            }
        });
        TFEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEntradaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFEntradaKeyTyped(evt);
            }
        });

        LblTitulo1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo1.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo1.setText("Posicion a calcular en la secuencia");
        LblTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LblTitulo.setFont(new java.awt.Font("Consolas", 1, 32)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("FIBONACCI");
        LblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TAMovimientos.setBackground(new java.awt.Color(67, 153, 161));
        TAMovimientos.setColumns(20);
        TAMovimientos.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        TAMovimientos.setForeground(new java.awt.Color(40, 51, 55));
        TAMovimientos.setRows(5);
        jScrollPane1.setViewportView(TAMovimientos);

        BtnVolver.setBackground(new java.awt.Color(40, 51, 55));
        BtnVolver.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(197, 226, 208));
        BtnVolver.setText("Volver");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnVolverMouseExited(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addContainerGap(492, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(401, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22))
                .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //Ejercicio 3
    public void fibonacci(int a, int primero, int segundo, int i){
        if (a<1){
            TAMovimientos.append("Solo se permiten numeros enteros mayores a cero (0)\n");
        }
        else{
            if (i<a){
                if (i==1){
                    TAMovimientos.append("1"+"\n");
                    TAMovimientos.append("0+1= 1"+"\n");
                    i+=2;
            }
            int tercero = primero + segundo;
            TAMovimientos.append(primero + "+" + segundo + "= " + tercero+"\n");
            primero = segundo;
            segundo =  tercero;
            //System.out.println(tercero);
            i++;
            fibonacci (a, primero, segundo, i);
            }
        }
    }
    
    
    
    
    private void TFEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEntradaActionPerformed

    private void TFEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            fibonacci(Integer.parseInt(TFEntrada.getText())+1,1,1,1);
        }
    }//GEN-LAST:event_TFEntradaKeyPressed

    private void TFEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyTyped
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_TFEntradaKeyTyped

    private void BtnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseEntered
        inter.ColorSelected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseEntered

    private void BtnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseExited
        inter.ColorUnselected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseExited

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        inter.op();
    }//GEN-LAST:event_BtnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JTextArea TAMovimientos;
    private javax.swing.JTextField TFEntrada;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
