/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicadeejercicios;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Guillermo
 */
public class Hexadecimal extends javax.swing.JPanel {

    /**
     * Creates new form Hexadecimal
     */
    private Interfaz inter;
    private Hexadecimal hexa;
    public Hexadecimal(Interfaz inter) {
        initComponents();
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnContador = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        TFEntrada = new javax.swing.JTextField();
        LblTitulo1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        LblTitulo3 = new javax.swing.JLabel();
        TFSalida = new javax.swing.JTextField();
        LblTitulo4 = new javax.swing.JLabel();
        TFSalida1 = new javax.swing.JTextField();

        BtnContador.setBackground(new java.awt.Color(40, 51, 55));
        BtnContador.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnContador.setForeground(new java.awt.Color(197, 226, 208));
        BtnContador.setText("Contador");
        BtnContador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnContador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnContadorMouseExited(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Consolas", 1, 32)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("TRADUCTOR HEXADECIMAL");
        LblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFEntrada.setBackground(new java.awt.Color(67, 153, 161));
        TFEntrada.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        TFEntrada.setForeground(new java.awt.Color(40, 51, 55));
        TFEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEntradaActionPerformed(evt);
            }
        });
        TFEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEntradaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFEntradaKeyTyped(evt);
            }
        });

        LblTitulo1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo1.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo1.setText("Introduzca el número que desea traducir");
        LblTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnVolver.setBackground(new java.awt.Color(40, 51, 55));
        BtnVolver.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(197, 226, 208));
        BtnVolver.setText("Volver");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnVolverMouseExited(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        LblTitulo3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo3.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo3.setText("Número traducido a hexadecimal");
        LblTitulo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFSalida.setBackground(new java.awt.Color(67, 153, 161));
        TFSalida.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        TFSalida.setForeground(new java.awt.Color(40, 51, 55));
        TFSalida.setEnabled(false);
        TFSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalidaActionPerformed(evt);
            }
        });

        LblTitulo4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo4.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo4.setText("Número traducido en base B(B=3)");
        LblTitulo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFSalida1.setBackground(new java.awt.Color(67, 153, 161));
        TFSalida1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        TFSalida1.setForeground(new java.awt.Color(40, 51, 55));
        TFSalida1.setEnabled(false);
        TFSalida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalida1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LblTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TFSalida1)))
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Ejercicio 1
    public void hexadecimal(int x, String y){
        if (x>0){
            switch(x%16){
                case 0: hexadecimal(x/16, "0"+y); break;
                case 1: hexadecimal(x/16, "1"+y); break;
                case 2: hexadecimal(x/16, "2"+y); break;
                case 3: hexadecimal(x/16, "3"+y); break;
                case 4: hexadecimal(x/16, "4"+y); break;
                case 5: hexadecimal(x/16, "5"+y); break;
                case 6: hexadecimal(x/16, "6"+y); break;
                case 7: hexadecimal(x/16, "7"+y); break;
                case 8: hexadecimal(x/16, "8"+y); break;
                case 9: hexadecimal(x/16, "9"+y); break;
                case 10: hexadecimal(x/16, "A"+y); break;
                case 11: hexadecimal(x/16, "B"+y); break;
                case 12: hexadecimal(x/16, "C"+y); break;
                case 13: hexadecimal(x/16, "D"+y); break;
                case 14: hexadecimal(x/16, "E"+y); break;
                case 15: hexadecimal(x/16, "F"+y); break;
            }
        }
        else{
            System.out.println("Hexadecimal: "+y);
            TFSalida.setText(y);
        }
    }
    public void ggcimal(int x, String y){
        if (x>0){
            switch(x%3){
                case 0: ggcimal(x/3, "0"+y); break;
                case 1: ggcimal(x/3, "1"+y); break;
                case 2: ggcimal(x/3, "2"+y); break;
            }
        }
        else{
            System.out.println("Ggcimal: "+y);
            TFSalida1.setText(y);
        }
    }
    
    
    
    private void TFEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEntradaActionPerformed

    private void BtnContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContadorMouseEntered
        
    }//GEN-LAST:event_BtnContadorMouseEntered

    private void BtnContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContadorMouseExited
        
    }//GEN-LAST:event_BtnContadorMouseExited

    private void BtnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseEntered
        inter.ColorSelected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseEntered

    private void BtnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseExited
        inter.ColorUnselected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseExited

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        inter.op();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void TFSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalidaActionPerformed

    private void TFEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            hexadecimal(Integer.parseInt(TFEntrada.getText()), "");
            ggcimal(Integer.parseInt(TFEntrada.getText()), "");
        }
    }//GEN-LAST:event_TFEntradaKeyPressed

    private void TFEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyTyped
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_TFEntradaKeyTyped

    private void TFSalida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalida1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContador;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo3;
    private javax.swing.JLabel LblTitulo4;
    private javax.swing.JTextField TFEntrada;
    private javax.swing.JTextField TFSalida;
    private javax.swing.JTextField TFSalida1;
    // End of variables declaration//GEN-END:variables
}
