/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicadeejercicios;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Guillermo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    Fondo fondo = new Fondo();

    public Interfaz() {
        this.setContentPane(fondo);
        setResizable(false);
        initComponents();
        
        Opciones op = new Opciones(this);
        PanelSetter(op);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenido.setOpaque(false);

        javax.swing.GroupLayout PanelContenidoLayout = new javax.swing.GroupLayout(PanelContenido);
        PanelContenido.setLayout(PanelContenidoLayout);
        PanelContenidoLayout.setHorizontalGroup(
            PanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        PanelContenidoLayout.setVerticalGroup(
            PanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void op(){
        Opciones op = new Opciones(this);
        PanelSetter(op);
    }
    public void hexa(){
        Hexadecimal hexa = new Hexadecimal(this);
        PanelSetter(hexa);
    }
    public void suma(){
        Suma suma = new Suma(this);
        PanelSetter(suma);
    }
    public void fibo(){
        Fibonacci fibo = new Fibonacci(this);
        PanelSetter(fibo);
    }
    public void deter(){
        Determinante deter = new Determinante(this);
        PanelSetter(deter);
    }
    public void tabla(){
        Tabla tabla = new Tabla(this);
        PanelSetter(tabla);
    }
    public void ciu(){
        Ciudades ciu = new Ciudades(this);
        PanelSetter(ciu);
    }
    public void poten(){
        Potencia poten = new Potencia(this);
        PanelSetter(poten);
    }
    public void facto(){
        Factorial facto = new Factorial(this);
        PanelSetter(facto);
    }
    public void palin(){
        Palindromo palin = new Palindromo(this);
        PanelSetter(palin);
    }
    public void inver(){
        Invertir inver = new Invertir(this);
        PanelSetter(inver);
    }
    public void cont(){
        Contador cont = new Contador(this);
        PanelSetter(cont);
    }
    
    public void PanelSetter(JPanel panel){
        panel.setSize(854, 480);
        panel.setLocation(0, 0);
        PanelContenido.removeAll();
        PanelContenido.add(panel, BorderLayout.CENTER);
        PanelContenido.revalidate();
        PanelContenido.repaint();
        PanelContenido.setOpaque(false);
        panel.setOpaque(false);
    }
    
    public void ColorSelected(JButton btn){
        btn.setBackground(Color.decode("#14ABA4"));
        btn.setForeground(Color.decode("#283337"));
    }
    public void ColorUnselected(JButton btn){
        btn.setBackground(Color.decode("#283337"));
        btn.setForeground(Color.decode("#C5E2D0"));
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenido;
    // End of variables declaration//GEN-END:variables

    class Fondo extends JPanel{
        private Image bmo;
        public void paint (Graphics grafico){
            bmo = new ImageIcon(getClass().getResource("Fondo.jpg")).getImage();
            grafico.drawImage(bmo, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(grafico);
        }
    }
    
}
