/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicadeejercicios;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Guillermo
 */
public class Opciones extends javax.swing.JPanel {

    /**
     * Creates new form Opciones
     */
    private Interfaz inter;
    public Opciones(Interfaz inter) {
        initComponents();
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnTabla = new javax.swing.JButton();
        BtnHexadecimal = new javax.swing.JButton();
        BtnSuma = new javax.swing.JButton();
        BtnCiudades = new javax.swing.JButton();
        BtnPalindromo = new javax.swing.JButton();
        BtnInvertir = new javax.swing.JButton();
        BtnFibonacci = new javax.swing.JButton();
        BtnPotencia = new javax.swing.JButton();
        BtnContador = new javax.swing.JButton();
        BtnDeterminante = new javax.swing.JButton();
        BtnFactorial = new javax.swing.JButton();

        jPanel1.setOpaque(false);

        BtnTabla.setBackground(new java.awt.Color(40, 51, 55));
        BtnTabla.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BtnTabla.setForeground(new java.awt.Color(197, 226, 208));
        BtnTabla.setText("Tabla de Multiplicar");
        BtnTabla.setToolTipText("");
        BtnTabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnTabla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnTablaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnTablaMouseExited(evt);
            }
        });
        BtnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTablaActionPerformed(evt);
            }
        });

        BtnHexadecimal.setBackground(new java.awt.Color(40, 51, 55));
        BtnHexadecimal.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnHexadecimal.setForeground(new java.awt.Color(197, 226, 208));
        BtnHexadecimal.setText("Hexadecimal");
        BtnHexadecimal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnHexadecimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHexadecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnHexadecimalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnHexadecimalMouseExited(evt);
            }
        });
        BtnHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHexadecimalActionPerformed(evt);
            }
        });

        BtnSuma.setBackground(new java.awt.Color(40, 51, 55));
        BtnSuma.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnSuma.setForeground(new java.awt.Color(197, 226, 208));
        BtnSuma.setText("Suma Recursiva");
        BtnSuma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSumaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSumaMouseExited(evt);
            }
        });
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        BtnCiudades.setBackground(new java.awt.Color(40, 51, 55));
        BtnCiudades.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnCiudades.setForeground(new java.awt.Color(197, 226, 208));
        BtnCiudades.setText("Ciudades");
        BtnCiudades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnCiudades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCiudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCiudadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCiudadesMouseExited(evt);
            }
        });
        BtnCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCiudadesActionPerformed(evt);
            }
        });

        BtnPalindromo.setBackground(new java.awt.Color(40, 51, 55));
        BtnPalindromo.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnPalindromo.setForeground(new java.awt.Color(197, 226, 208));
        BtnPalindromo.setText("Palíndromo");
        BtnPalindromo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnPalindromo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPalindromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPalindromoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPalindromoMouseExited(evt);
            }
        });
        BtnPalindromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPalindromoActionPerformed(evt);
            }
        });

        BtnInvertir.setBackground(new java.awt.Color(40, 51, 55));
        BtnInvertir.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnInvertir.setForeground(new java.awt.Color(197, 226, 208));
        BtnInvertir.setText("Invertir Texto");
        BtnInvertir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnInvertir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnInvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnInvertirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnInvertirMouseExited(evt);
            }
        });
        BtnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvertirActionPerformed(evt);
            }
        });

        BtnFibonacci.setBackground(new java.awt.Color(40, 51, 55));
        BtnFibonacci.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnFibonacci.setForeground(new java.awt.Color(197, 226, 208));
        BtnFibonacci.setText("Fibonacci");
        BtnFibonacci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnFibonacci.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnFibonacci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnFibonacciMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnFibonacciMouseExited(evt);
            }
        });
        BtnFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFibonacciActionPerformed(evt);
            }
        });

        BtnPotencia.setBackground(new java.awt.Color(40, 51, 55));
        BtnPotencia.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnPotencia.setForeground(new java.awt.Color(197, 226, 208));
        BtnPotencia.setText("Potenciación");
        BtnPotencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnPotencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPotencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPotenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPotenciaMouseExited(evt);
            }
        });
        BtnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPotenciaActionPerformed(evt);
            }
        });

        BtnContador.setBackground(new java.awt.Color(40, 51, 55));
        BtnContador.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnContador.setForeground(new java.awt.Color(197, 226, 208));
        BtnContador.setText("Contador");
        BtnContador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnContador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnContadorMouseExited(evt);
            }
        });
        BtnContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContadorActionPerformed(evt);
            }
        });

        BtnDeterminante.setBackground(new java.awt.Color(40, 51, 55));
        BtnDeterminante.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnDeterminante.setForeground(new java.awt.Color(197, 226, 208));
        BtnDeterminante.setText("Determinante");
        BtnDeterminante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnDeterminante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnDeterminante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnDeterminanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnDeterminanteMouseExited(evt);
            }
        });
        BtnDeterminante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeterminanteActionPerformed(evt);
            }
        });

        BtnFactorial.setBackground(new java.awt.Color(40, 51, 55));
        BtnFactorial.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnFactorial.setForeground(new java.awt.Color(197, 226, 208));
        BtnFactorial.setText("Factorial");
        BtnFactorial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnFactorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnFactorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnFactorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnFactorialMouseExited(evt);
            }
        });
        BtnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFactorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDeterminante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnPalindromo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnInvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnContador, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDeterminante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnFibonacci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnContador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInvertir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPalindromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void BtnHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHexadecimalActionPerformed
        inter.hexa();
    }//GEN-LAST:event_BtnHexadecimalActionPerformed

    private void BtnHexadecimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHexadecimalMouseEntered
        inter.ColorSelected(BtnHexadecimal);
    }//GEN-LAST:event_BtnHexadecimalMouseEntered

    private void BtnHexadecimalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHexadecimalMouseExited
        inter.ColorUnselected(BtnHexadecimal);
    }//GEN-LAST:event_BtnHexadecimalMouseExited

    private void BtnSumaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSumaMouseEntered
        inter.ColorSelected(BtnSuma);
    }//GEN-LAST:event_BtnSumaMouseEntered

    private void BtnSumaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSumaMouseExited
        inter.ColorUnselected(BtnSuma);
    }//GEN-LAST:event_BtnSumaMouseExited

    private void BtnFibonacciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFibonacciMouseEntered
        inter.ColorSelected(BtnFibonacci);
    }//GEN-LAST:event_BtnFibonacciMouseEntered

    private void BtnFibonacciMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFibonacciMouseExited
        inter.ColorUnselected(BtnFibonacci);
    }//GEN-LAST:event_BtnFibonacciMouseExited

    private void BtnDeterminanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeterminanteMouseEntered
        inter.ColorSelected(BtnDeterminante);
    }//GEN-LAST:event_BtnDeterminanteMouseEntered

    private void BtnDeterminanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeterminanteMouseExited
        inter.ColorUnselected(BtnDeterminante);
    }//GEN-LAST:event_BtnDeterminanteMouseExited

    private void BtnTablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTablaMouseEntered
        inter.ColorSelected(BtnTabla);
    }//GEN-LAST:event_BtnTablaMouseEntered

    private void BtnTablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTablaMouseExited
        inter.ColorUnselected(BtnTabla);
    }//GEN-LAST:event_BtnTablaMouseExited

    private void BtnCiudadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCiudadesMouseEntered
        inter.ColorSelected(BtnCiudades);
    }//GEN-LAST:event_BtnCiudadesMouseEntered

    private void BtnCiudadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCiudadesMouseExited
        inter.ColorUnselected(BtnCiudades);
    }//GEN-LAST:event_BtnCiudadesMouseExited

    private void BtnPotenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPotenciaMouseEntered
        inter.ColorSelected(BtnPotencia);
    }//GEN-LAST:event_BtnPotenciaMouseEntered

    private void BtnPotenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPotenciaMouseExited
        inter.ColorUnselected(BtnPotencia);
    }//GEN-LAST:event_BtnPotenciaMouseExited

    private void BtnFactorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFactorialMouseEntered
        inter.ColorSelected(BtnFactorial);
    }//GEN-LAST:event_BtnFactorialMouseEntered

    private void BtnFactorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFactorialMouseExited
        inter.ColorUnselected(BtnFactorial);
    }//GEN-LAST:event_BtnFactorialMouseExited

    private void BtnPalindromoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPalindromoMouseEntered
        inter.ColorSelected(BtnPalindromo);
    }//GEN-LAST:event_BtnPalindromoMouseEntered

    private void BtnPalindromoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPalindromoMouseExited
        inter.ColorUnselected(BtnPalindromo);
    }//GEN-LAST:event_BtnPalindromoMouseExited

    private void BtnInvertirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInvertirMouseEntered
        inter.ColorSelected(BtnInvertir);
    }//GEN-LAST:event_BtnInvertirMouseEntered

    private void BtnInvertirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInvertirMouseExited
        inter.ColorUnselected(BtnInvertir);
    }//GEN-LAST:event_BtnInvertirMouseExited

    private void BtnContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContadorMouseEntered
        inter.ColorSelected(BtnContador);
    }//GEN-LAST:event_BtnContadorMouseEntered

    private void BtnContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContadorMouseExited
        inter.ColorUnselected(BtnContador);
    }//GEN-LAST:event_BtnContadorMouseExited

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        inter.suma();
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFibonacciActionPerformed
        inter.fibo();
    }//GEN-LAST:event_BtnFibonacciActionPerformed

    private void BtnDeterminanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeterminanteActionPerformed
        inter.deter();
    }//GEN-LAST:event_BtnDeterminanteActionPerformed

    private void BtnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTablaActionPerformed
        inter.tabla();
    }//GEN-LAST:event_BtnTablaActionPerformed

    private void BtnCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCiudadesActionPerformed
        inter.ciu();
    }//GEN-LAST:event_BtnCiudadesActionPerformed

    private void BtnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPotenciaActionPerformed
        inter.poten();
    }//GEN-LAST:event_BtnPotenciaActionPerformed

    private void BtnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFactorialActionPerformed
        inter.facto();
    }//GEN-LAST:event_BtnFactorialActionPerformed

    private void BtnPalindromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPalindromoActionPerformed
        inter.palin();
    }//GEN-LAST:event_BtnPalindromoActionPerformed

    private void BtnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvertirActionPerformed
        inter.inver();
    }//GEN-LAST:event_BtnInvertirActionPerformed

    private void BtnContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContadorActionPerformed
        inter.cont();
    }//GEN-LAST:event_BtnContadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCiudades;
    private javax.swing.JButton BtnContador;
    private javax.swing.JButton BtnDeterminante;
    private javax.swing.JButton BtnFactorial;
    private javax.swing.JButton BtnFibonacci;
    private javax.swing.JButton BtnHexadecimal;
    private javax.swing.JButton BtnInvertir;
    private javax.swing.JButton BtnPalindromo;
    private javax.swing.JButton BtnPotencia;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JButton BtnTabla;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
