/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicadeejercicios;

import java.awt.event.KeyEvent;

/**
 *
 * @author Guillermo
 */
public class Potencia extends javax.swing.JPanel {

    /**
     * Creates new form Potencia
     */
    private Interfaz inter;
    public Potencia(Interfaz inter) {
        initComponents();
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        TFEntrada = new javax.swing.JTextField();
        LblTitulo2 = new javax.swing.JLabel();
        TFEntrada1 = new javax.swing.JTextField();
        TFSalida = new javax.swing.JTextField();
        LblTitulo3 = new javax.swing.JLabel();

        LblTitulo1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo1.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo1.setText("Introduzca la base");
        LblTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnVolver.setBackground(new java.awt.Color(40, 51, 55));
        BtnVolver.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(197, 226, 208));
        BtnVolver.setText("Volver");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 20, 20), 4, true));
        BtnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnVolverMouseExited(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Consolas", 1, 32)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("POTENCIACIÓN");
        LblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFEntrada.setBackground(new java.awt.Color(67, 153, 161));
        TFEntrada.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        TFEntrada.setForeground(new java.awt.Color(40, 51, 55));
        TFEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEntradaActionPerformed(evt);
            }
        });
        TFEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEntradaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFEntradaKeyTyped(evt);
            }
        });

        LblTitulo2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo2.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo2.setText("Introduzca el exponente");
        LblTitulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TFEntrada1.setBackground(new java.awt.Color(67, 153, 161));
        TFEntrada1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        TFEntrada1.setForeground(new java.awt.Color(40, 51, 55));
        TFEntrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEntrada1ActionPerformed(evt);
            }
        });
        TFEntrada1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEntrada1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFEntrada1KeyTyped(evt);
            }
        });

        TFSalida.setBackground(new java.awt.Color(67, 153, 161));
        TFSalida.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        TFSalida.setForeground(new java.awt.Color(40, 51, 55));
        TFSalida.setEnabled(false);
        TFSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalidaActionPerformed(evt);
            }
        });

        LblTitulo3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblTitulo3.setForeground(new java.awt.Color(197, 226, 208));
        LblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo3.setText("Resultado de la potenciación");
        LblTitulo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(TFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                    .addComponent(LblTitulo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))))))
            .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(LblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(188, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(LblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Ejercicio 7.1
    public void potencia(int x, int y, int a){
        if (x<1){
            TFSalida.setText("0");
            y=1;
        }
        if (y<1){
            x=1;
            y=1;
        }
        if (y>1){
            x= x*a;
            potencia(x, y-1, a);
        }
        else{
            TFSalida.setText(String.valueOf(x)+"\n");
        }
    }
    
    
    private void BtnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseEntered
        inter.ColorSelected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseEntered

    private void BtnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseExited
        inter.ColorUnselected(BtnVolver);
    }//GEN-LAST:event_BtnVolverMouseExited

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        inter.op();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void TFEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEntradaActionPerformed

    private void TFEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            TFEntrada1.requestFocus();
        }
    }//GEN-LAST:event_TFEntradaKeyPressed

    private void TFEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntradaKeyTyped
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_TFEntradaKeyTyped

    private void TFEntrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEntrada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEntrada1ActionPerformed

    private void TFEntrada1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntrada1KeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            potencia(Integer.parseInt(TFEntrada.getText()),Integer.parseInt(TFEntrada1.getText()),Integer.parseInt(TFEntrada.getText()));
        }
    }//GEN-LAST:event_TFEntrada1KeyPressed

    private void TFEntrada1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEntrada1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_TFEntrada1KeyTyped

    private void TFSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo2;
    private javax.swing.JLabel LblTitulo3;
    private javax.swing.JTextField TFEntrada;
    private javax.swing.JTextField TFEntrada1;
    private javax.swing.JTextField TFSalida;
    // End of variables declaration//GEN-END:variables
}
